version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    ports:
      - "2379:2379"
    command: >
      /usr/local/bin/etcd
      --name s1
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd:2379

  etcdkeeper:
    image: evildecay/etcdkeeper
    ports:
      - "8080:8080"
    environment:
      ETCD_SERVER: http://etcd:2379

  nginx:
    image: openresty/openresty:alpine
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/lua:/etc/nginx/lua

  confd:
    image: kelseyhightower/confd
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./confd:/etc/confd
    command: >
      -backend etcd
      -node http://etcd:2379
      -interval 10

  git-sync:
    image: k8s.gcr.io/git-sync/git-sync:v3.3.1
    environment:
      - GIT_SYNC_REPO=https://github.com/your/repo.git
      - GIT_SYNC_BRANCH=main
      - GIT_SYNC_ROOT=/git
      - GIT_SYNC_DEST=sync
      - GIT_SYNC_WAIT=30
    volumes:
      - ./nginx:/git

  node-api:
    build: ./node-services
    ports:
      - "3000:3000"
